<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">
   <channel>
      <title>BashBar's Changelog</title>
      <link>http://you.com/app/appcast.xml</link>
      <description>Most recent changes with links to updates.</description>
      <language>en</language>
         <item>
            <title>Version 1.8</title>
						<sparkle:releaseNotesLink>
							https://github.com/tbrek/BashBar/releases/tag/v.1.6
						</sparkle:releaseNotesLink>
            <pubDate>Wed, 09 Jan 2006 19:20:11 +0000</pubDate>
            <enclosure url="http://you.com/app/Your Great App 2.0.zip" sparkle:version="1.8" length="1623481" type="application/octet-stream"  />
         </item>

   </channel>
</rss>