<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">
   <channel>
      <title>BashBar's Changelog</title>
      <link>https://raw.githubusercontent.com/tbrek/BashBar/master/_includes/appcast.inc</link>
      <description>Most recent changes with links to updates.</description>
      <language>en</language>
      <item>
          <title>Version 2.0 (2 bugs fixed; 3 new features)</title>
          <sparkle:releaseNotesLink>
            https://example.com/release_notes/app_2.0.html
          </sparkle:releaseNotesLink>
          <pubDate>Mon, 05 Oct 2015 19:20:11 +0000</pubDate>
          <enclosure url="https://example.com/downloads/app.zip.or.dmg.or.tar.etc"
                     sparkle:version="2.0"
                     length="0"
                     type="application/octet-stream" />
      </item>
   </channel>
</rss>